### ISSUE TITLE
Attributes from Server Not Displayed on Client

### ISSUE THREAD

**Issue by rxay579** [AlmostReliable/attributetooltipfix#2]
### Minecraft Version

1.20.1

### Mod Version

Attribute-Tooltip-Fix-Fabric-1.20.1-2.0.1

### Describe the bug!

Using along with CIA v1.1.0 (https://modrinth.com/mod/cia) in a custom mod list.
The environment is a local server running for a small number of clients.
CIA is installed on the server and Attributes Tooltip Fix is installed on both server and client.

When CIA is installed on the client, has custom attributes set on the client, and using this mod: the additions (damage/armor) are visible on the tooltip in a single player world.

When CIA is installed on the server only, has custom attributes set on the server, and using this mod: the additions (damage/armor) are not visible on the tooltip on a connected client.

When CIA is installed on the server and client, has custom attributes set on the server, and using this mod: the additions (damage/armor) are not visible on the tooltip on a connected client.

Using a PlayerEx attributes screen (and live testing), the additional attributes appear to be active, but they aren't displayed on the item's tooltip.

If I'm doing something wrong (config issue) or additional information is needed, let me know.

### Log

https://gist.github.com/rxay579/3e38de2d5d510d2790c3ff57c34012fd

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by LLytho** [comment]
Hey,

can you provide me some configs I can use for CIA which may result into the issue? 
And I have to ask, does the issue only occour if CIA and ATF are both installed? Because ATF does not touch the tooltips at all

**Comment by rxay579** [comment]
Wouldn't let me upload a JSON5, so changed the extension by adding a .txt; please remove that for the config to work.
[custom_item_attributes.json5.txt](https://github.com/AlmostReliable/attributetooltipfix/files/14796354/custom_item_attributes.json5.txt)

I don't expect the tooltip for the extra damage on the "minecraft:stick" to be visible.
The other items I'm presently modifying are from RelicEx and BetterEnd.

With CIA alone (single player or server/client), I hadn't seen any reference to the changed attributes in the item stats or tooltips.
Was hoping this mod would fix that as it was able to show the extra damage/armor values in single player.
*edited for clarity*

**Comment by rxay579** [comment]
Here is a config for just the "minecraft:wooden_sword" if you want to skip testing with RelicEx and BetterEnd.
[custom_item_attributes.json5.txt](https://github.com/AlmostReliable/attributetooltipfix/files/14796420/custom_item_attributes.json5.txt)

**Comment by LLytho** [comment]
> With CIA alone (single player or server/client), I hadn't seen any reference to the changed attributes in the item stats or tooltips.
Was hoping this mod would fix that as it was able to show the extra damage/armor values in single player.

ATF sadly can't fix that. I don't know how CIA updates the attributes, but if they are not sending them to the client, they can't be shown in the tooltips.
